#!/usr/bin/env python3
"""
Builds and runs the config self-test.

The shared layer is written for Roblox: it uses Color3, Vector3, Random, and it
resolves its dependencies through `require(script.Parent.Thing)`. None of that
exists in the standalone luau interpreter, and its sandbox will not let a script
override the global `require` to fake it.

So this bundles instead. Each module is wrapped as

    modules["shared/Config/Pets"] = function(script, require) <file> end

which turns `script` and `require` into ordinary parameters that shadow the
globals the file expects, with no sandbox to fight. Roblox globals are stubbed in
a prelude the wrapped modules close over. Then tools/selftest.luau runs on top and
asserts.

    python3 tools/selftest.py

Needs `luau` on PATH, or pass its path as the first argument. Get one from
https://github.com/luau-lang/luau/releases.
"""

from __future__ import annotations

import os
import shutil
import subprocess
import sys
import tempfile
from pathlib import Path

ROOT = Path(__file__).resolve().parent.parent
SHARED = ROOT / "src" / "shared"
BODY = ROOT / "tools" / "selftest.luau"

PRELUDE = r"""
-- Generated by tools/selftest.py. Do not edit.
-- Stubs for the Roblox globals the shared layer touches, plus the module loader.

local Color3 = {}
Color3.__index = Color3

local function makeColor(r, g, b)
	return setmetatable({ R = r, G = g, B = b }, Color3)
end

function Color3.new(r, g, b)
	return makeColor(r or 0, g or 0, b or 0)
end

function Color3.fromRGB(r, g, b)
	return makeColor(r / 255, g / 255, b / 255)
end

function Color3:Lerp(other, alpha)
	return makeColor(
		self.R + (other.R - self.R) * alpha,
		self.G + (other.G - self.G) * alpha,
		self.B + (other.B - self.B) * alpha
	)
end

function Color3:ToHex()
	return string.format("%02X%02X%02X", self.R * 255, self.G * 255, self.B * 255)
end

local Vector3 = {}
Vector3.__index = Vector3

function Vector3.new(x, y, z)
	return setmetatable({ X = x or 0, Y = y or 0, Z = z or 0 }, Vector3)
end

-- A small deterministic generator standing in for Roblox's Random. It only has to
-- be uniform enough that the egg distribution check means something.
local Random = {}
Random.__index = Random

function Random.new(seed)
	return setmetatable({ state = math.floor(math.abs(seed or 1)) % 2147483646 + 1 }, Random)
end

function Random:_next()
	self.state = (self.state * 16807) % 2147483647
	return self.state / 2147483647
end

function Random:NextNumber(min, max)
	if min == nil then
		return self:_next()
	end
	return min + self:_next() * (max - min)
end

function Random:NextInteger(min, max)
	local span = max - min + 1
	return min + math.floor(self:_next() * span) % span
end

local task = {
	spawn = function(fn, ...)
		fn(...)
	end,
	delay = function(_, fn, ...)
		fn(...)
	end,
	wait = function() end,
}

local modules = {}
local loaded = {}
local nodes = {}

-- Stands in for the Instance tree Rojo would build, so `script.Parent.Pets`
-- resolves the same way it does in game.
local function node(path)
	local key = table.concat(path, "/")
	if nodes[key] then
		return nodes[key]
	end

	local created = setmetatable({ __path = path }, {
		__index = function(_, field)
			local next_ = table.clone(path)
			if field == "Parent" then
				table.remove(next_)
			else
				table.insert(next_, field)
			end
			return node(next_)
		end,
		__tostring = function()
			return key
		end,
	})

	nodes[key] = created
	return created
end

local function moduleRequire(target)
	local key = table.concat(rawget(target, "__path"), "/")
	if loaded[key] ~= nil then
		return loaded[key]
	end

	local factory = modules[key]
	if not factory then
		error(`selftest: no module bundled at "{key}"`, 0)
	end

	local result = factory(target, moduleRequire)
	loaded[key] = result
	return result
end

local function shared(...)
	return moduleRequire(node({ "shared", ... }))
end
"""


def wrap(key: str, source: str) -> str:
    return f'modules["{key}"] = function(script, require)\n{source}\nend\n'


def build() -> str:
    parts = [PRELUDE]

    for file in sorted(SHARED.rglob("*.lua")):
        relative = file.relative_to(SHARED.parent)
        key = relative.with_suffix("").as_posix()
        parts.append(wrap(key, file.read_text().rstrip()))

    parts.append(BODY.read_text())
    return "\n".join(parts)


def main() -> int:
    interpreter = sys.argv[1] if len(sys.argv) > 1 else shutil.which("luau")
    if not interpreter or not os.path.exists(interpreter):
        print("luau interpreter not found.")
        print("Install it from https://github.com/luau-lang/luau/releases,")
        print("then run:  python3 tools/selftest.py [path/to/luau]")
        return 2

    bundle = build()

    with tempfile.NamedTemporaryFile("w", suffix=".luau", delete=False) as handle:
        handle.write(bundle)
        path = handle.name

    try:
        result = subprocess.run([interpreter, path], capture_output=True, text=True)
        # Rewrite temp-file line numbers out of any traceback so failures point at
        # something a reader can act on.
        output = (result.stdout + result.stderr).replace(path, "<bundle>")
        print(output.rstrip())
        return result.returncode
    finally:
        os.unlink(path)


if __name__ == "__main__":
    sys.exit(main())
